### ISSUE TITLE
Overbodige stations 

### ISSUE THREAD

**Issue by bendelathouwer** [meyskens/ris-at-home#1]
Heb even je project project bekeken, goed Idee maar er staan alvast 2 stations in waar van ik weet dat die al lang niet meer toegankelijk zijn Antwerpen dam en oost namelijk. Dus mijn vraag is waarom staan die mee in je lijst?

**Comment by meyskens** [comment]
De lijst komt direct van https://github.com/iRail/stations, ook buitenlandse stations hebben weinig nut aangezien de iRail API enkel diensten naar Belgie kent. Een 2de lijst onderhouden is iets teveel werk daarom houd ik het op een 1:1 kopie.
